// To generate a new stimulus controller : ./bin/rails g stimulus controller_name
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import TabsController from "./tabs_controller.js"
application.register("tabs", TabsController)
